if Holo.Options:GetValue("Hud") then 
	Holo:Post(HUDPlayerCustody, "init", function(self)
		local custody_panel = self._hud_panel:child("custody_panel")
		local timer = custody_panel:child("timer")
		local timer_msg = custody_panel:child("timer_msg")
		timer:set_font_size(24)
		timer_msg:set_font_size(24)
		self._hud.trade_text1:set_alpha(0)		
		self._hud.trade_text2:set_w(0)
		custody_panel:child("trade_delay"):set_alpha(0)
		custody_panel:child("civilians_killed"):set_alpha(0)
		self:update_texts()
		Holo:AddUpdateFunc(callback(self, self, "update_texts"))
	end)
	Holo:Post(HUDPlayerCustody, "set_respawn_type", function(self)
		self:update_texts()
	end)
	function HUDPlayerCustody:update_texts()
		local custody_panel = self._hud_panel:child("custody_panel")
		local timer = custody_panel:child("timer")
		local timer_msg = custody_panel:child("timer_msg")
		local t = timer:text()

		timer:set_text("00:00")
		managers.hud:make_fine_text(timer)
		timer:set_text(t)
		timer:set_w(timer:w() + 2)
		timer:set_align("center")
		managers.hud:make_fine_text(timer_msg)

		timer_msg:set_world_center_x(custody_panel:w() / 2 - timer:w() / 2)
		timer_msg:set_world_y(managers.hud._hud_heist_timer._heist_timer_panel:world_bottom() + 2)
		timer:set_text(t)
		timer:set_position(timer_msg:right() + 2, timer_msg:y() + 1)
	end
end