Holo:Post(CrimeSpreeMissionButton, "init", function(self)
	self._mission_image:configure({blend_mode = "normal"})
	self._mission_image:set_layer(1)
	self._highlight:configure({blend_mode = "normal", color = Holo:GetColor("Colors/Marker")})
	self._highlight:set_layer(2)
	self._active_border:set_layer(3)
end)

Holo:Post(CrimeSpreeMissionButton, "refresh", function(self)
	self._active_border:set_visible(true)
end)

Holo:Post(CrimeSpreeStartButton, "init", function(self)
	self._highlight:configure({blend_mode = "normal", color = Holo:GetColor("Colors/Marker")})
end)