if Holo:ShouldModify("Menu", "Lobby") then
	Holo:Post(HUDPackageUnlockedItem, "init", function(self)
		Holo.Utils:SetBlendMode(self._panel)
	end)
	Holo:Post(HUDStageEndScreen, "init", function(self)
		self._background_layer_full:child("stage_text"):hide()
		Holo.Utils:SetBlendMode(self._foreground_layer_safe)
		self._box._panel:hide()
		self._package_box._panel:hide()
		self._paygrade_panel:hide()
		local pg_text = self._foreground_layer_safe:child("pg_text") 
		pg_text:set_text(managers.localization:to_upper_text(tweak_data.difficulty_name_ids[Global.game_settings.difficulty]))		
		managers.hud:make_fine_text(pg_text)		
		pg_text:set_right(self._paygrade_panel:right())
	end)
	Holo:Post(HUDStageEndScreen, "stage_spin_up", function(self)
		self._lp_text:set_font_size(48)
	end)
end