Hooks:PostHook(WalletGuiObject, "set_object_visible", "HoloSetObjectVisible", function()
	Holo:ModifyWallet()
end)
Hooks:PostHook(WalletGuiObject, "set_object_visible", "HoloSetObjectVisible", function()
	Holo:ModifyWallet()
end)
Hooks:PostHook(WalletGuiObject, "set_wallet", "HoloSetWallet", function()
	Holo:ModifyWallet()
end)
Hooks:PostHook(WalletGuiObject, "refresh", "HoloRefresh", function()
	Holo:ModifyWallet()
end)
if GoonBase then
	Hooks:Add("WalletGuiObjectOnSetWallet", "HoloWalletGuiObjectOnSetWallet", function()
		Holo:ModifyWallet()
	end)	
	Hooks:Add("WalletGuiObjectOnRefresh", "HoloWalletGuiObjectOnRefresh", function()
		Holo:ModifyWallet()
	end)	
	Hooks:Add("WalletGuiObjectSetObjectVisible", "HoloWalletGuiObjectSetObjectVisible", function()
		Holo:ModifyWallet()
	end)
end