if Holo.Options:GetValue("Menu") then 
	Holo:Post(WalletGuiObject, "set_object_visible", function()
		Holo.Utils:ModifyWallet()
	end)
	Holo:Post(WalletGuiObject, "set_object_visible", function()
		Holo.Utils:ModifyWallet()
	end)
	Holo:Post(WalletGuiObject, "set_wallet", function()
		Holo.Utils:ModifyWallet()
	end)
	Holo:Post(WalletGuiObject, "refresh", function()
		Holo.Utils:ModifyWallet()
	end)
	if GoonBase then
		Hooks:Add("WalletGuiObjectOnSetWallet", "HoloWalletGuiObjectOnSetWallet", function()
			Holo.Utils:ModifyWallet()
		end)	
		Hooks:Add("WalletGuiObjectOnRefresh", "HoloWalletGuiObjectOnRefresh", function()
			Holo.Utils:ModifyWallet()
		end)	
		Hooks:Add("WalletGuiObjectSetObjectVisible", "HoloWalletGuiObjectSetObjectVisible", function()
			Holo.Utils:ModifyWallet()
		end)
	end
end